# Generated by Django 5.1.6 on 2025-03-04 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_remove_usuario_groups_remove_usuario_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='username',
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre_completo',
            field=models.CharField(default='Usuario sin nombre', max_length=150, unique=True),
        ),
    ]
